export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  registerSuccess: "/register/success",
  verifyEmail: "/verify-email",
  onboarding: "/onboarding",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  tenantsNew: "/tenants/new",
  tenantBase: "/tenants/:slug",
  admin: "/admin",
  settingsSessions: "/settings/sessions",
  userDesktop: "/u/:profileId",
} as const;
