export const routePaths = {
  home: "/",
  login: "/login",
  register: "/register",
  registerSuccess: "/register/success",
  verifyEmail: "/verify-email",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  tenantsNew: "/tenants/new",
  tenantRoles: "/tenants/:slug/roles",
  tenantMembers: "/tenants/:slug/members",
  admin: "/admin",
  settingsSessions: "/settings/sessions",
} as const;
